### ISSUE TITLE
'Cannot read property 'options' of undefined' when calling `checkScreen`

### ISSUE THREAD

**Issue by MortenGregersen** [wswebcreation/webdriver-image-comparison#2] opened 2019-04-12 11:58 UTC
**Environment (please complete the following information):**
 - Node.js version: 10.15.3
 - NPM version: 6.9.0
 - Browser name and version: Chrome 73
 - Platform name and version: macOS 10.14
 - Framework name and version: WebdriverIO 5.7.2
 - Plugin name and version: _homemade_
 - webdriver-image-comparison version: 0.1.0

**Config of the automation framework + plugin**
```js
config.framework = 'jasmine';
config.capabilities = [
  {
    maxInstances: 5,
    browserName: 'chrome',
    'goog:chromeOptions': {
        args: []
    }
  },
];
```

**Describe the bug**
When I call `checkScreen` in the middle of my test with WebdriverIO I get the error: 
`Cannot read property 'options' of undefined`

I don't get a stracktrace for where the error happens, but it happens in the call to `checkScreen`.

**To Reproduce**
This is not very beautiful, but a quick and dirty way to get the values for making the call to `checkScreen`.

```ts
import { BaseClass, checkScreen } from 'webdriver-image-comparison';
import { Methods } from 'webdriver-image-comparison/build/methods/methods.interface';
import { InstanceData } from 'webdriver-image-comparison/build/methods/instanceData.interfaces';
import { CheckScreenOptions } from 'webdriver-image-comparison/build/commands/screen.interfaces';
import { ImageCompareResult } from 'webdriver-image-comparison/build/methods/images.interfaces';
import { ComparisonResult } from '../screenshots/comparison-result';

export async function webCompareScreen(tag): Promise<ComparisonResult> {
  const base = new BaseClass({});
  const methods: Methods = {
    executor: browser.executeScript,
    screenShot: browser.takeScreenshot,
  };
  const instanceData = getInstanceData();
  const folders = base.folders;
  const checkScreenOptions: CheckScreenOptions = {
    wic: base.defaultOptions,
    method: {},
  };
  const imageCompareResult = (await checkScreen(
    methods,
    instanceData,
    folders,
    tag,
    checkScreenOptions
  )) as ImageCompareResult;
  return imageCompareResult as ComparisonResult;
}

function getInstanceData(): InstanceData {
  // @ts-ignore Driver is given magically by Webdriverio
  const capabilities = driver.capabilities;
  return {
    browserName: capabilities.browserName,
    deviceName: '',
    logName: '',
    name: '',
    nativeWebScreenshot: false,
    platformName: '',
  };
}
```

**Expected behavior**
I expected to get an `ImageCompareResult`.

**Log**
```
[chrome #0-0] TypeError: Cannot read property 'options' of undefined
[chrome #0-0]     at <Jasmine>
[chrome #0-0]     at <Jasmine>
```

**Comment by wswebcreation** [comment] 2019-04-13 09:17
Tnx for filling an issue

I'll check it when I get back

**Comment by wswebcreation** [comment] 2019-04-15 18:27
I found the issue, now need to know where and how to fix it. The problem is in the 

```js
  const methods: Methods = {
    executor: browser.executeScript,
    screenShot: browser.takeScreenshot,
  };
```

The first time the `executor` is being called it fails.

**Comment by wswebcreation** [comment] 2019-04-20 07:44
Going to close this one because there is a module now specifically  for WebdriverIO

**Closed by wswebcreation** 2019-04-20 07:44 UTC
Labels: bug

**Comment by zbyte64** [comment] 2023-09-08 01:59
Having a similar issue `Cannot read properties of undefined (reading 'options')` but with save/checkElement - but using the latest webdriverio 8 & mocha and node 18.
